INSERT INTO SYS_ALARM_TB (UPDATEDATE,MGWID,CATEGORY,ERRORLEVEL,STATE,ERRORID,DETAIL) VALUES (sysdate(),{SERVER_ID},'CPU','','E','','');
INSERT INTO SYS_ALARM_TB (UPDATEDATE,MGWID,CATEGORY,ERRORLEVEL,STATE,ERRORID,DETAIL) VALUES (sysdate(),{SERVER_ID},'MEMORY','','E','','');
INSERT INTO SYS_ALARM_TB (UPDATEDATE,MGWID,CATEGORY,ERRORLEVEL,STATE,ERRORID,DETAIL) VALUES (sysdate(),{SERVER_ID},'DISK','','E','','');
INSERT INTO SYS_ALARM_TB (UPDATEDATE,MGWID,CATEGORY,ERRORLEVEL,STATE,ERRORID,DETAIL) VALUES (sysdate(),{SERVER_ID},'PROCESS','','E','','');
INSERT INTO SYS_ALARM_TB (UPDATEDATE,MGWID,CATEGORY,ERRORLEVEL,STATE,ERRORID,DETAIL) VALUES (sysdate(),{SERVER_ID},'QUEUE','','E','','');
