INSERT INTO SYS_FILESYSTEM_TB(MGWID,FILESYSTEM) values({SERVER_ID},'/');
INSERT INTO SYS_FILESYSTEM_TB(MGWID,FILESYSTEM) values({SERVER_ID},'/dev');
INSERT INTO SYS_FILESYSTEM_TB(MGWID,FILESYSTEM) values({SERVER_ID},'/boot');
INSERT INTO SYS_FILESYSTEM_TB(MGWID,FILESYSTEM) values({SERVER_ID},'/run');
