INSERT INTO SYS_THRESHOLD_TB(MGWID,ELEMENT,CRITICAL,MAJOR,MINOR) VALUES ({SERVER_ID},'MEMORY',91,81,71);
INSERT INTO SYS_THRESHOLD_TB(MGWID,ELEMENT,CRITICAL,MAJOR,MINOR) VALUES ({SERVER_ID},'DISK',99,95,90);
INSERT INTO SYS_THRESHOLD_TB(MGWID,ELEMENT,CRITICAL,MAJOR,MINOR) VALUES ({SERVER_ID},'CPU',5,10,15);
INSERT INTO SYS_THRESHOLD_TB(MGWID,ELEMENT,CRITICAL,MAJOR,MINOR) VALUES ({SERVER_ID},'QUEUE',90,50,10);
