TRUNCATE TABLE MANAGER_TB;
ALTER TABLE MANAGER_TB AUTO_INCREMENT=1;
INSERT INTO MANAGER_TB
(MN_LEVEL,MN_ID,MN_PW,MN_NAME,MN_IPADDR,MN_EMAIL,MN_CELL_PHONE,MN_DESC,MN_CREATE_TIME) 
VALUES 
(1,'admin','$2b$10$QwLlMETrW0OfKEzBKiy2QesmlQ5zw9Cigd1HILcfHIwsd3Re.5B2a','','0.0.0.0','','','',sysdate());
COMMIT;
