CREATE TABLE SYS_ALARM_TB (
UPDATEDATE DATETIME	NOT NULL COMMENT '기록시간',
MGWID INTEGER(4) NOT NULL COMMENT '시스템ID',
CATEGORY VARCHAR(20) NOT NULL COMMENT 'SYS_THRESHOLD_TB에 정의된 ELEMENT',
ERRORLEVEL VARCHAR(10) COMMENT 'SYS_OMC_ERROR_TB에 정의된 ERRORLEVEL',
STATE CHAR(1) COMMENT 'E:해지, S:발생',
ERRORID VARCHAR(40) COMMENT 'SYS_OMC_ERROR_TB에 정의된 ERRORID',
DETAIL VARCHAR(1000) COMMENT '상세정보',
PRIMARY KEY(MGWID,CATEGORY)
) ENGINE=Aria DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
