CREATE TABLE {DISK_HISTORY} ( 
DKH_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
DK_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT 'TB 고유번호',
DK_NAME	VARCHAR(128) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NOT NULL COMMENT '이름',
DK_DRIVE_TYPE INT(10) UNSIGNED NULL DEFAULT '0' COMMENT '드라이브 유형',
DK_FILE_SYSTEM VARCHAR(32) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '파일시스템 종류',
DK_ACCESS TINYINT(3) UNSIGNED NULL DEFAULT '0' COMMENT '미디어 엑세스 유형',
DK_VOLUME_NAME VARCHAR(32) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '볼륨명',
DK_VOLUME_SN VARCHAR(16) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '볼륨 시리얼 번호',
DK_DESC	VARCHAR(128) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '설명',
DK_PHYSICAL_SN VARCHAR(64) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '시리얼 번호',
DK_INTERFACE_TYPE VARCHAR(32) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '인터페이스 종류',
DK_MF VARCHAR(128) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '제조사',
DK_MODEL VARCHAR(64) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '모델명',
DK_DETECT_TIME DATETIME DEFAULT NULL COMMENT '데이터 검출 시간',
DK_PREV_HIST_SQ TEXT DEFAULT NULL COMMENT '과거 히스토리 고유번호 묶음',
DK_SUMMARY TEXT DEFAULT NULL COMMENT '변동사항',
HB_SQ BIGINT(20) UNSIGNED NOT NULL COMMENT 'HW_BASE_TB 고유번호',
US_SQ BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'USER_TB 고유번호',
DKH_RECORD_TIME	DATETIME NULL COMMENT '기록시간',
PRIMARY KEY(DKH_SQ)  
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX {DISK_HISTORY}_IDX1 ON {DISK_HISTORY} (DK_SQ);
CREATE INDEX {DISK_HISTORY}_IDX2 ON {DISK_HISTORY} (HB_SQ);
CREATE INDEX {DISK_HISTORY}_IDX3 ON {DISK_HISTORY} (US_SQ);
CREATE INDEX {DISK_HISTORY}_IDX4 ON {DISK_HISTORY} (DK_DETECT_TIME);
