CREATE TABLE {PROCESS_HISTORY} ( 
PSH_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
PS_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT 'TB 고유번호',
PS_FILE_NAME VARCHAR(128) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NOT NULL COMMENT '프로세스 파일명',
PS_TYPE tinyint(1) DEFAULT '0' COMMENT '0:화이트,1:블랙',
PS_FILE_PATH VARCHAR(512) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '파일 경로',
PS_ORIGINAL_FILE_NAME VARCHAR(128) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '원본파일명',
PS_COMPANY_NAME VARCHAR(64) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '제작사명',
PS_FILE_DESC VARCHAR(128) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '파일 설명',
PS_FILE_VER VARCHAR(32) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '파일 버전',
PS_COPY_RIGHT VARCHAR(64) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '저작권 정보',
PS_RUNNING BOOL NULL DEFAULT '0' COMMENT '실행 여부',
PS_CONNECTED_SVR_ADDR TEXT NULL COMMENT '프로세스가 접속한 서버 주소(IP:PORT 권장, 세미콜론으로 다중 저장)',
PS_DETECT_TIME DATETIME DEFAULT NULL COMMENT '데이터 검출 시간',
PS_PREV_HIST_SQ TEXT DEFAULT NULL COMMENT '과거 히스토리 고유번호 묶음',
PS_SUMMARY TEXT DEFAULT NULL COMMENT '변동사항',
HB_SQ BIGINT(20) UNSIGNED NOT NULL COMMENT 'HW_BASE_TB 고유번호',
US_SQ BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'USER_TB 고유번호',
PSH_RECORD_TIME DATETIME NULL COMMENT '기록시간',
PRIMARY KEY(PSH_SQ) 
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX {PROCESS_HISTORY}_IDX1 ON {PROCESS_HISTORY} (PS_SQ);
CREATE INDEX {PROCESS_HISTORY}_IDX2 ON {PROCESS_HISTORY} (HB_SQ);
CREATE INDEX {PROCESS_HISTORY}_IDX3 ON {PROCESS_HISTORY} (US_SQ);
CREATE INDEX {PROCESS_HISTORY}_IDX4 ON {PROCESS_HISTORY} (PS_DETECT_TIME);
