CREATE TABLE NET_PRINTER_TB (
NP_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
NP_CONNECTED TINYINT(1) DEFAULT '0' COMMENT '접속 가능 여부',
NP_DISCORDANCE TINYINT(1) DEFAULT '0' COMMENT '검출된프린터데이터의이상정보',
NP_WEB_CONNECT TINYINT(1) DEFAULT '0' COMMENT '프린터웹서비스접속성공 여부',
NP_HOST_NAME VARCHAR(128) NOT NULL COMMENT '네트워크 프린터명',
NP_WSD_PRINTER_DEVICE TINYINT(1) DEFAULT '0' COMMENT 'WSD프린터 장비 여부',
NP_WSD_LOCATION VARCHAR(64) DEFAULT '' COMMENT 'NP_WSD_PRINTER_DEVICE가 TRUE인 경우 IPV6 주소',
NP_OPEN_PORT VARCHAR(256) DEFAULT '' COMMENT '열린 PORT 번호 목록, 세미콜론으로 분리해서 다중입력',
NP_PRINTER_PORT VARCHAR(256) DEFAULT '' COMMENT 'PRINTER PORT 중현재LISTEN중인포트',
NP_WEB_TEXT VARCHAR(128) DEFAULT '' COMMENT 'HTTP, HTTPS로 접속 후 수신한 문자열에서 검출한 키워드 문자열(EX. IPTIME, ETC)',
NP_DETECT_TIME DATETIME DEFAULT NULL COMMENT '데이터 검출 시간',
NP_CURR_HIST_SQ BIGINT(20) UNSIGNED DEFAULT NULL COMMENT '현재 히스토리 고유번호',
NP_CURR_HIST_DATE VARCHAR(8) DEFAULT NULL COMMENT '현재 히스토리 날짜',
NP_PREV_HIST_SQ TEXT DEFAULT NULL COMMENT '과거 히스토리 고유번호 묶음',
NP_SUMMARY TEXT DEFAULT NULL COMMENT '변동사항',
HB_SQ BIGINT(20) UNSIGNED NOT NULL COMMENT 'HW_BASE_TB 고유번호',
US_SQ BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'USER_TB 고유번호',
PRIMARY KEY (NP_SQ)
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX NET_PRINTER_TB_IDX1 ON NET_PRINTER_TB (HB_SQ);
CREATE INDEX NET_PRINTER_TB_IDX2 ON NET_PRINTER_TB (US_SQ);
