CREATE TABLE USER_GROUP_LINK_TB (
UG_SQ_P BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT '상위 사용자그룹 고유번호',
UG_SQ_C BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT '하위 사용자그룹 고유번호',
UG_FLAG CHAR(1) DEFAULT 'A' COMMENT '스케줄러 작업 상태',
PRIMARY KEY(UG_SQ_P,UG_SQ_C)
) ENGINE=Aria DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX USER_GROUP_LINK_TB_IDX1 ON USER_GROUP_LINK_TB (UG_FLAG);
