CREATE TABLE {STD_EVENT_HISTORY} (
STDH_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
STD_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT 'TB 고유번호',
STD_RECORD_TIME VARCHAR(13) NOT NULL COMMENT '데이터 검출 시간(HOUR)',
STD_IPADDR VARCHAR(15) NOT NULL COMMENT '이벤트발생 IP',
STD_US_SQ BIGINT(20) NOT NULL COMMENT '이벤트발생 US_SQ',
STD_UG_SQ BIGINT(20) NOT NULL COMMENT '이벤트발생 UG_SQ',
STD_TYPE SMALLINT(3) NOT NULL COMMENT '이벤트 유형',
STD_LEVEL SMALLINT(1) NOT NULL COMMENT '이벤트 레벨',
STD_EXIST SMALLINT(1) NOT NULL COMMENT '0:해제,1:발생,2:중복,3:강제확인,4:강제삭제',
STD_COUNT INT DEFAULT '0' COMMENT '합계',
STDH_RECORD_TIME DATETIME NOT NULL COMMENT '기록시간',
PRIMARY KEY (STDH_SQ),
UNIQUE KEY (STD_RECORD_TIME,STD_IPADDR,STD_US_SQ,STD_TYPE,STD_LEVEL,STD_EXIST)
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX {STD_EVENT_HISTORY}_IDX1 ON {STD_EVENT_HISTORY} (STD_UG_SQ);
