CREATE TABLE SYNC_GROUP_TB (
DEPT_CODE VARCHAR(10) NOT NULL COMMENT '부서코드',
DEPT_NAME VARCHAR(100) DEFAULT NULL COMMENT '부서명',
DEPT_DESC VARCHAR(128) DEFAULT NULL COMMENT '부서에대한설명',
UPDEPT_CODE VARCHAR(10) DEFAULT NULL COMMENT '상위부서코드',
DEPT_DATE VARCHAR(10) DEFAULT NULL COMMENT '부서일자',
PRIMARY KEY (DEPT_CODE)
) ENGINE=Aria DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
