CREATE TABLE {USER_LINK_HISTORY} (
ULH_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
UG_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT '사용자그룹 고유번호',
US_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT '사용자 고유번호',
UL_FLAG CHAR(1) NOT NULL COMMENT '스케줄러 작업 상태',
ULH_RECORD_TIME DATETIME NULL COMMENT '기록 시간',
PRIMARY KEY (ULH_SQ)
) ENGINE=Aria DEFAULT CHARSET=utf8 PAGE_CHECKSUM=1 ROW_FORMAT=PAGE;
CREATE INDEX {USER_LINK_HISTORY}_IDX1 ON {USER_LINK_HISTORY} (US_SQ,UG_SQ);
