CREATE TABLE RULE_DETECT_LINK_TB (
RU_SQ BIGINT(20) UNSIGNED ZEROFILL DEFAULT NULL COMMENT '정책 고유번호',
TARGET_SQ BIGINT(20) UNSIGNED ZEROFILL DEFAULT NULL COMMENT '객체or그룹 고유번호',
TARGET_IS_GROUP TINYINT(1) DEFAULT '0' COMMENT '0:OBJECT, 1:GROUP',
TARGET_TYPE TINYINT(2) DEFAULT '0' COMMENT '0:BLACK, 1:WHITE, 2:ACCESS, 3:CONEXT',
RDL_FLAG CHAR(1) DEFAULT 'A' COMMENT '스케줄러 작업 상태',
RDL_INT_DATA1 int(11) DEFAULT 0 COMMENT 'CPU 사용률(%)',
RDL_INT_DATA2 int(11) DEFAULT 0 COMMENT 'CPU 사용시간(sec)',
RDL_INT_DATA3 int(11) DEFAULT 0 COMMENT 'CPU 사용률 제한(%)'
) ENGINE=Aria DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX RULE_DETECT_LINK_TB_IDX1 ON RULE_DETECT_LINK_TB (RDL_FLAG);
CREATE INDEX RULE_DETECT_LINK_TB_IDX2 ON RULE_DETECT_LINK_TB (RU_SQ,TARGET_SQ,TARGET_IS_GROUP,TARGET_TYPE);