CREATE TABLE NET_CONNECTION_TB (
NC_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
NC_LOCAL_NAME VARCHAR(128) NOT NULL COMMENT '드라이브 지정명',
NC_CONNECTION_STATE TINYINT(3) UNSIGNED DEFAULT '0' COMMENT '접속 상태',
NC_CONNECTION_TYPE INT(1) UNSIGNED DEFAULT '0' COMMENT '연결 분류',
NC_DESC VARCHAR(256) DEFAULT NULL COMMENT '설명',
NC_PROVIDER_NAME VARCHAR(128) DEFAULT '' COMMENT '연결에 사용되는 네트워크 공급자',
NC_REMOTE_NAME VARCHAR(128) DEFAULT '' COMMENT '원격지 이름',
NC_REMOTE_PATH VARCHAR(128) DEFAULT '' COMMENT '원격지 경로(드라이브 UNC)',
NC_DISPLAY_TYPE CHAR(16) DEFAULT '' COMMENT '원격접속 출력 종류',
NC_RESOURCE_TYPE CHAR(16) DEFAULT '' COMMENT '원격접속 자원 종류',
NC_DETECT_TIME DATETIME DEFAULT NULL COMMENT '데이터 검출 시간',
NC_CURR_HIST_SQ BIGINT(20) UNSIGNED DEFAULT NULL COMMENT '현재 히스토리 고유번호',
NC_CURR_HIST_DATE VARCHAR(8) DEFAULT NULL COMMENT '현재 히스토리 날짜',
NC_PREV_HIST_SQ TEXT DEFAULT NULL COMMENT '과거 히스토리 고유번호 묶음',
NC_SUMMARY TEXT DEFAULT NULL COMMENT '변동사항',
HB_SQ BIGINT(20) UNSIGNED NOT NULL COMMENT 'HW_BASE_TB 고유번호',
US_SQ BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'USER_TB 고유번호',
PRIMARY KEY (NC_SQ)
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX NET_CONNECTION_TB_IDX1 ON NET_CONNECTION_TB (HB_SQ);
CREATE INDEX NET_CONNECTION_TB_IDX2 ON NET_CONNECTION_TB (US_SQ);
