CREATE TABLE DETECT_PROCESS_TB (
DP_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유 번호',
DP_PROCESS_NAME VARCHAR(32) NOT NULL COMMENT '프로세스 파일명',
DP_PROTECTION  TINYINT(1) DEFAULT '0' COMMENT '프로세스 보호 활성여부 0:비활성화 1:활성화',
DP_DETAIL_INFO TINYINT(1) DEFAULT '0' COMMENT '프로세스 상세정보 0 or 1, 2:virtual',
DP_HASH CHAR(32) DEFAULT '' COMMENT '프로세스 파일 HASH',
DP_DESC VARCHAR(128) DEFAULT '' COMMENT '프로세스에 대한 추가 설명',
DP_USE TINYINT(1) DEFAULT '1' COMMENT '등록정보 사용 여부',
DP_FLAG CHAR(1) DEFAULT 'A' COMMENT '스케줄러플래그',
PRIMARY KEY (DP_SQ)
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX DETECT_PROCESS_TB_IDX1 ON DETECT_PROCESS_TB (DP_PROCESS_NAME);
CREATE INDEX DETECT_PROCESS_TB_IDX2 ON DETECT_PROCESS_TB (DP_FLAG);