CREATE TABLE STATS_GW_TB (
SG_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
SG_CLASS_IP CHAR(11) DEFAULT NULL COMMENT 'C-CLASS IP주소',
SG_DEFAULT_MAC CHAR(17) DEFAULT NULL COMMENT '2개 이상 대표 MAC주소',
SG_RECORD_TIME DATETIME DEFAULT NULL COMMENT '마지막 변경 시간',
PRIMARY KEY (SG_SQ)
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX STATS_GW_TB_IDX1 ON STATS_GW_TB(SG_CLASS_IP);
