CREATE TABLE INFRARED_DEVICE_TB (
ID_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
ID_NAME VARCHAR(128) DEFAULT '' COMMENT '객체가 알려진 레이블',
ID_MF VARCHAR(128) DEFAULT '' COMMENT '제조사',
ID_PROTOCOL_SUPPORTED INT(5) UNSIGNED DEFAULT '0' COMMENT '컨트롤러가 제어된 장치에 엑세스하는데 사용하는 프로토콜',
ID_STATUS VARCHAR(10) DEFAULT '' COMMENT '개체의 현재 상태',
ID_STATUS_INFO INT(5) UNSIGNED DEFAULT '0' COMMENT '논리 장치의 상태',
ID_DETECT_TIME DATETIME DEFAULT NULL COMMENT '데이터 검출 시간',
ID_CURR_HIST_SQ BIGINT(20) UNSIGNED DEFAULT NULL COMMENT '현재 히스토리 고유번호',
ID_CURR_HIST_DATE VARCHAR(8) DEFAULT NULL COMMENT '현재 히스토리 날짜',
ID_PREV_HIST_SQ TEXT DEFAULT NULL COMMENT '과거 히스토리 고유번호 묶음',
ID_SUMMARY TEXT DEFAULT NULL COMMENT '변동사항',
HB_SQ BIGINT(20) UNSIGNED NOT NULL COMMENT 'HW_BASE_TB 고유번호',
US_SQ BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'USER_TB 고유번호',
PRIMARY KEY (ID_SQ)
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX INFRARED_DEVICE_TB_IDX1 ON INFRARED_DEVICE_TB (HB_SQ);
CREATE INDEX INFRARED_DEVICE_TB_IDX2 ON INFRARED_DEVICE_TB (US_SQ);
