CREATE TABLE {SYNC_GROUP_HISTORY} (
SGH_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
DEPT_CODE VARCHAR(10) NOT NULL COMMENT '부서코드',
DEPT_NAME VARCHAR(100) DEFAULT NULL COMMENT '부서명',
DEPT_DESC VARCHAR(128) DEFAULT NULL COMMENT '부서에대한설명',
UPDEPT_CODE VARCHAR(10) DEFAULT NULL COMMENT '상위부서코드',
DEPT_DATE VARCHAR(10) DEFAULT NULL COMMENT '부서일자',
SGH_RECORD_TIME DATETIME NULL COMMENT '기록시간',
PRIMARY KEY(SGH_SQ)
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX {SYNC_GROUP_HISTORY}_IDX1 ON {SYNC_GROUP_HISTORY} (DEPT_CODE);
