CREATE TABLE SYS_CONFIG_CHANGE_TB (
MGWID INTEGER(3) NOT NULL COMMENT '시스템ID',
CHGFLAG INTEGER(1) NOT NULL COMMENT '0:해지, 1:변경',
PROCESS VARCHAR(20) COMMENT '프로세스명',
NAME VARCHAR(80) COMMENT 'CHANGE FILE PATH',
PRIMARY KEY(MGWID,PROCESS,NAME)
) ENGINE=Aria DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
