CREATE TABLE {RULE_DETECT_LINK_HISTORY} (
RDLH_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
RU_SQ BIGINT(20) UNSIGNED ZEROFILL DEFAULT NULL COMMENT '정책 고유번호',
TARGET_SQ BIGINT(20) UNSIGNED ZEROFILL DEFAULT NULL COMMENT '객체or그룹 고유번호',
TARGET_IS_GROUP TINYINT(1) DEFAULT '0' COMMENT '0:OBJECT, 1:GROUP',
TARGET_TYPE TINYINT(2) DEFAULT '0' COMMENT '0:BLACK, 1:WHITE, 2:ACCESS, 3:CONEXT',
RDL_FLAG CHAR(1) DEFAULT 'A' COMMENT '스케줄러 작업 상태',
RDLH_RECORD_TIME datetime DEFAULT NULL COMMENT '기록시간',
PRIMARY KEY(RDLH_SQ)
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX {RULE_DETECT_LINK_HISTORY}_IDX1 ON {RULE_DETECT_LINK_HISTORY} (RU_SQ,TARGET_TYPE);
