CREATE TABLE {RULE_EXCEPT_HISTORY} (
REH_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
RE_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT 'RULE_EXCEPT_TB 고유번호',
RU_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT '정책 고유번호',
MN_SQ BIGINT(20) UNSIGNED DEFAULT '0' COMMENT '정책 수정 관리자',
RE_TYPE TINYINT(2) UNSIGNED DEFAULT '0' COMMENT '정책 번호',
RE_CATEGORY VARCHAR(30) DEFAULT NULL COMMENT '정책 항목',
RE_POS TINYINT(2) DEFAULT NULL COMMENT '정책 적용 위치 0:유저,1:그룹,2:IP',
RE_VALUE VARCHAR(50) DEFAULT NULL COMMENT '정책 적용 값',
RE_DESC VARCHAR(255) DEFAULT NULL COMMENT '정책 적용 설명',
RE_USE TINYINT(1) DEFAULT '0' COMMENT '등록 정책 사용여부',
RE_FLAG CHAR(1) NOT NULL COMMENT '스케줄러 작업상태',
REH_RECORD_TIME DATETIME DEFAULT NULL COMMENT '기록시간',
PRIMARY KEY (REH_SQ)
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX {RULE_EXCEPT_HISTORY}_IDX1 ON {RULE_EXCEPT_HISTORY} (RE_SQ);
CREATE INDEX {RULE_EXCEPT_HISTORY}_IDX2 ON {RULE_EXCEPT_HISTORY} (RE_TYPE);
