CREATE TABLE WIN_DRV_TB (
DV_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
DV_CLASS VARCHAR(15) DEFAULT ''  COMMENT '드라이버클래스명',
DV_CLASS_DESC VARCHAR(128) DEFAULT '' COMMENT '드라이버클래스설명',
DV_DESC VARCHAR(128) DEFAULT '' COMMENT '드라이버설명',
DV_DRIVER VARCHAR(128) DEFAULT '' COMMENT '드라이버명',
DV_ENUM VARCHAR(50) DEFAULT '' COMMENT '드라이버분류나열',
DV_FILE_COMPANY VARCHAR(30) DEFAULT '' COMMENT '드라이버파일제조사정보',
DV_FILE_COPY_RIGHT VARCHAR(128) DEFAULT '' COMMENT '드라이버파일저작권정보',
DV_FILE_DESC VARCHAR(128) DEFAULT '' COMMENT '드라이버파일설명',
DV_FILE_PATH VARCHAR(128) DEFAULT '' COMMENT '드라이버파일경로',
DV_FILE_PRODUCT VARCHAR(30) DEFAULT '' COMMENT '드라이버파일상품정보',
DV_FILE_VER VARCHAR(15) DEFAULT '' COMMENT '드라이버파일버전',
DV_LOCATION VARCHAR(128) DEFAULT '' COMMENT '드라이버에등록된위치정보',
DV_MFG VARCHAR(128) DEFAULT '' COMMENT '드라이버제조사정보',
DV_NAME VARCHAR(128) DEFAULT '' COMMENT '드라이버명',
DV_SERVICE VARCHAR(30) DEFAULT '' COMMENT '드라이버서비스명',
DV_START VARCHAR(15) DEFAULT '' COMMENT '드라이버시작정보',
DV_STATUS VARCHAR(15) DEFAULT '' COMMENT '드라이버시작상태',
DV_TYPE VARCHAR(30) DEFAULT '' COMMENT '드라이버타입',
DV_DATA_TYPE TINYINT(2) UNSIGNED DEFAULT '1' COMMENT '1:추가,2:제거',
DV_DETECT_TIME DATETIME DEFAULT NULL COMMENT '데이터 검출 시간',
DV_CURR_HIST_SQ BIGINT(20) UNSIGNED DEFAULT NULL COMMENT '현재 히스토리 고유번호',
DV_CURR_HIST_DATE VARCHAR(8) DEFAULT NULL COMMENT '현재 히스토리 날짜',
DV_PREV_HIST_SQ TEXT DEFAULT NULL COMMENT '과거 히스토리 고유번호 묶음',
HB_SQ BIGINT(20) UNSIGNED NOT NULL COMMENT 'HW_BASE_TB 고유번호',
US_SQ BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'USER_TB 고유번호',
PRIMARY KEY (DV_SQ)
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX WIN_DRV_TB_IDX1 ON WIN_DRV_TB (HB_SQ);
CREATE INDEX WIN_DRV_TB_IDX2 ON WIN_DRV_TB (US_SQ);
CREATE INDEX WIN_DRV_TB_IDX3 ON WIN_DRV_TB (DV_DRIVER,DV_NAME,DV_SERVICE);
