CREATE TABLE {DETECT_GROUP_HISTORY} (
DGH_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
DG_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT 'PROCESS OR WATCH 고유번호',
DG_NAME CHAR(32) DEFAULT '' COMMENT 'PROCESS OR WATCH 그룹명',
DG_SNO CHAR(32) DEFAULT '' COMMENT 'PROCESS OR WATCH 그룹 식별번호',
DG_DESC VARCHAR(128) DEFAULT '' COMMENT 'PROCESS OR WATCH 그룹에 대한 추가 설명',
DG_FLAG CHAR(1) NOT NULL COMMENT '스케줄러 작업 상태',
DGH_RECORD_TIME DATETIME DEFAULT NULL COMMENT '기록시간',
PRIMARY KEY (DGH_SQ)
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX {DETECT_GROUP_HISTORY}_IDX1 ON {DETECT_GROUP_HISTORY} (DG_SQ);
