CREATE TABLE {BLUETOOTH_HISTORY} ( 
BTH_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
BT_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT 'TB 고유번호',
BT_INSTANCE_NAME VARCHAR(128) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '블루투스 디바이스 인스턴스명',
BT_MAC_ADDR VARCHAR(32) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '블루투스 MAC 주소',
BT_DEVICE VARCHAR(128) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '디바이스 분류',
BT_MINOR_DEVICE VARCHAR(64) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '디바이스 분류 상세',
BT_DANGER BOOL NULL DEFAULT '0' COMMENT '위험성',
BT_CONNECTED BOOL NULL DEFAULT '0' COMMENT '현재 접속 여부',
BT_AUTHENTICATED BOOL NULL DEFAULT '0' COMMENT '인증 여부',
BT_REMEMBERED BOOL NULL DEFAULT '0' COMMENT '페어링 여부',
BT_DETECT_TIME DATETIME DEFAULT NULL COMMENT '데이터 검출 시간',
BT_PREV_HIST_SQ TEXT DEFAULT NULL COMMENT '과거 히스토리 고유번호 묶음',
BT_SUMMARY TEXT DEFAULT NULL COMMENT '변동사항',
HB_SQ BIGINT(20) UNSIGNED NOT NULL COMMENT 'HW_BASE_TB 고유번호',
US_SQ BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'USER_TB 고유번호',
BTH_RECORD_TIME DATETIME NULL COMMENT '기록시간',
PRIMARY KEY(BTH_SQ) 
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX {BLUETOOTH_HISTORY}_IDX1 ON {BLUETOOTH_HISTORY} (BT_SQ);
CREATE INDEX {BLUETOOTH_HISTORY}_IDX2 ON {BLUETOOTH_HISTORY} (HB_SQ);
CREATE INDEX {BLUETOOTH_HISTORY}_IDX3 ON {BLUETOOTH_HISTORY} (US_SQ);
CREATE INDEX {BLUETOOTH_HISTORY}_IDX4 ON {BLUETOOTH_HISTORY} (BT_DETECT_TIME);
