CREATE TABLE {DISK_REG_LINK_HISTORY} (
DRH_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
DR_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT 'TB 고유번호',
HB_SQ BIGINT(20) UNSIGNED NOT NULL COMMENT 'HW_BASE_TB 고유번호',
DK_PHYSICAL_SN VARCHAR(64) DEFAULT '' COMMENT 'DISK 시리얼 번호',
DR_REG TINYINT(1) UNSIGNED DEFAULT 0 COMMENT '등록된 장치인지',
DR_FLAG CHAR(1) DEFAULT 'A' COMMENT '스케줄러 작업상태',
DRH_RECORD_TIME DATETIME DEFAULT NULL COMMENT '기록시간',
PRIMARY KEY(DRH_SQ)
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
