CREATE TABLE CONFIG_TB (
CF_NAME VARCHAR(64) NOT NULL COMMENT '환경설정명',
CF_VALUE VARCHAR(512) DEFAULT '' COMMENT '설정값',
CF_FLAG CHAR(1) DEFAULT 'A' COMMENT '스케줄러 작업 상태',
UNIQUE KEY CF_NAME_UK (CF_NAME)
) ENGINE=Aria DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX CONFIG_TB_IDX1 ON CONFIG_TB (CF_FLAG);