CREATE TABLE {NET_DRIVE_HISTORY} ( 
NDH_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
ND_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT 'TB 고유번호',
ND_DRIVE_NAME VARCHAR(128) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NOT NULL COMMENT '드라이브 지정 네임',
ND_USER_NAME VARCHAR(32) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '사용자명',
ND_CONNECTION_TYPE INT(1) UNSIGNED NULL DEFAULT '0' COMMENT '연결 분류(Drive/Print Redirection)',
ND_DEFER_FLAGS TINYINT(2) DEFAULT '0' COMMENT '드라이브를 로그온할 때 바로 연결하는지 여부',
ND_PROVIDER_NAME VARCHAR(128) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '연결에 사용되는 네트워크 공급자',
ND_PROVIDER_TYPE INT(10) UNSIGNED NULL DEFAULT '0' COMMENT '네트워크 드라이브에 연결하는데 사용되는 네트워크 공급자 유형',
ND_REMOTE_PATH VARCHAR(128) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '원격지 경로(드라이브 UNC)',
ND_DETECT_TIME DATETIME DEFAULT NULL COMMENT '데이터 검출 시간',
ND_PREV_HIST_SQ TEXT DEFAULT NULL COMMENT '과거 히스토리 고유번호 묶음',
ND_SUMMARY TEXT DEFAULT NULL COMMENT '변동사항',
HB_SQ BIGINT(20) UNSIGNED NOT NULL COMMENT 'HW_BASE_TB 고유번호',
US_SQ BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'USER_TB 고유번호',
NDH_RECORD_TIME DATETIME NULL COMMENT '기록시간',
PRIMARY KEY(NDH_SQ) 
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX {NET_DRIVE_HISTORY}_IDX1 ON {NET_DRIVE_HISTORY} (ND_SQ);
CREATE INDEX {NET_DRIVE_HISTORY}_IDX2 ON {NET_DRIVE_HISTORY} (HB_SQ);
CREATE INDEX {NET_DRIVE_HISTORY}_IDX3 ON {NET_DRIVE_HISTORY} (US_SQ);
CREATE INDEX {NET_DRIVE_HISTORY}_IDX4 ON {NET_DRIVE_HISTORY} (ND_DETECT_TIME);
