CREATE TABLE {CONNECT_EXT_HISTORY} (
CEH_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
CE_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT 'TB 고유번호',
CE_URL VARCHAR(64) NOT NULL COMMENT '시스템 이름',
CE_CONNECTED TINYINT(3) UNSIGNED DEFAULT '0' COMMENT '인터넷 가능여부 검사 결과',
CE_DETECT_TIME DATETIME DEFAULT NULL COMMENT '데이터 검출 시간',
CE_PREV_HIST_SQ TEXT DEFAULT NULL COMMENT '과거 히스토리 고유번호 묶음',
CE_SUMMARY TEXT DEFAULT NULL COMMENT '변동사항',
HB_SQ BIGINT(20) UNSIGNED NOT NULL COMMENT 'HW_BASE_TB 고유번호',
US_SQ BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'USER_TB 고유번호',
CEH_RECORD_TIME DATETIME NULL COMMENT '기록시간',
PRIMARY KEY(CEH_SQ)
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX {CONNECT_EXT_HISTORY}_IDX1 ON {CONNECT_EXT_HISTORY} (CE_SQ);
CREATE INDEX {CONNECT_EXT_HISTORY}_IDX2 ON {CONNECT_EXT_HISTORY} (HB_SQ);
CREATE INDEX {CONNECT_EXT_HISTORY}_IDX3 ON {CONNECT_EXT_HISTORY} (US_SQ);
CREATE INDEX {CONNECT_EXT_HISTORY}_IDX4 ON {CONNECT_EXT_HISTORY} (CE_DETECT_TIME);
