CREATE TABLE {BASE_STATUS_HISTORY} (
HB_SQ bigint(20) unsigned zerofill NOT NULL COMMENT 'HW_BASE_TB 고유번호',
ONOFF_STATUS CHAR(1) DEFAULT NULL COMMENT ' S : START , E : END ',
STATUS_TIME datetime DEFAULT sysdate() COMMENT 'Agent 수신시간',
PRIMARY KEY (HB_SQ, STATUS_TIME)
) ENGINE=Aria DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page; 
