CREATE TABLE UPGRADE_AGENT_TB (
UA_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
UA_ORDER SMALLINT(5) UNSIGNED DEFAULT '0' COMMENT '우선 번호',
UA_NAME VARCHAR(32) NOT NULL DEFAULT '' COMMENT '업데이트명',
UA_VERSION VARCHAR(16) NOT NULL DEFAULT '' COMMENT '업그레이드 버전',
UA_TARGET_TYPE TINYINT(2) NOT NULL DEFAULT '0' COMMENT '0:ALL,1:IP,2:그룹',
UA_TARGET_VALUE VARCHAR(31) NOT NULL DEFAULT '' COMMENT '적용값',
UA_DATE CHAR(8) NOT NULL DEFAULT '' COMMENT 'YYYYMMDD',
UA_TIME CHAR(6) NOT NULL DEFAULT '' COMMENT 'HHMMSS',
UA_USE TINYINT(1) NOT NULL DEFAULT '0' COMMENT '0:NOTUSE,1:USE',
UA_FLAG CHAR(1) DEFAULT 'A' COMMENT '스케줄러 작업 상태',
PRIMARY KEY (UA_SQ)
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX UPGRADE_AGENT_TB_IDX1 ON UPGRADE_AGENT_TB (UA_FLAG);
CREATE INDEX UPGRADE_AGENT_TB_IDX2 ON UPGRADE_AGENT_TB (UA_USE);
