CREATE TABLE SYS_PINFO_TB (
MGWID INTEGER(4) NOT NULL COMMENT '시스템ID',
IDX INTEGER(8) COMMENT '순번',
PNAME VARCHAR(20) NOT NULL COMMENT '프로세스명',
ARGS VARCHAR(100) COMMENT '아규먼트값',
MAXNUM INTEGER(8) COMMENT '',
STATUS CHAR(1) COMMENT 'S:정상, K:KILL',
PID INTEGER(8) COMMENT 'PID',
PPID INTEGER(8) COMMENT 'PARENT PID',
STIME INTEGER(10) COMMENT 'START TIME',
KTIME INTEGER(10) COMMENT 'KILL TIME',
PCPU INTEGER(8) COMMENT '% RECENT CPU TIME USED BY ALL LWPS',
PSIZE INTEGER(8) COMMENT 'RES 물리메모리 사용량',
PPRIORITY INTEGER(4) COMMENT '시스템우선순위',
AUTOFLAG CHAR(1) COMMENT 'A:자동, F:무시',
UPDATETIME  DATETIME COMMENT '최근갱신일자',
PRIMARY KEY(MGWID,IDX)
) ENGINE=Aria DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
