CREATE TABLE {ROUTER_HISTORY} ( 
RTH_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
RT_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT 'TB 고유번호',
RT_DETECT_TYPE SMALLINT(3) UNSIGNED NULL DEFAULT '0' COMMENT '공유기 검출 유형',
RT_IPADDR VARCHAR(16) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '공유기 IP 주소',
RT_MAC_ADDR VARCHAR(32) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '공유기 MAC 주소',
RT_WEB_TEXT VARCHAR(128) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT 'http, https로 접속 후 수신한 문자열에서 검출한 키워드 문자열(Ex. iptime, etc)',
RT_CAPTION VARCHAR(128) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '공유기 정보',
RT_DETECT_TIME DATETIME DEFAULT NULL COMMENT '데이터 검출 시간',
RT_PREV_HIST_SQ TEXT DEFAULT NULL COMMENT '과거 히스토리 고유번호 묶음',
RT_SUMMARY TEXT DEFAULT NULL COMMENT '변동사항',
HB_SQ BIGINT(20) UNSIGNED NOT NULL COMMENT 'HW_BASE_TB 고유번호',
US_SQ BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'USER_TB 고유번호',
RTH_RECORD_TIME DATETIME NULL COMMENT '기록시간',
PRIMARY KEY(RTH_SQ) 
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX {ROUTER_HISTORY}_IDX1 ON {ROUTER_HISTORY} (RT_SQ);
CREATE INDEX {ROUTER_HISTORY}_IDX2 ON {ROUTER_HISTORY} (HB_SQ);
CREATE INDEX {ROUTER_HISTORY}_IDX3 ON {ROUTER_HISTORY} (US_SQ);
CREATE INDEX {ROUTER_HISTORY}_IDX4 ON {ROUTER_HISTORY} (RT_DETECT_TIME);
