CREATE TABLE DETECT_LINK_TB (
DG_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT '감시 그룹 고유번호',
OBJECT_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT '감시(PROCESS or IP or URL) 고유번호',
OBJECT_TYPE TINYINT(2) DEFAULT '0' COMMENT '0:PROCESS, 1:IP, 2:URL',
DL_FLAG CHAR(1) DEFAULT 'A' COMMENT '스케줄러 작업 상태'
) ENGINE=Aria DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX DETECT_LINK_TB_IDX1 ON DETECT_LINK_TB (DL_FLAG);
CREATE INDEX DETECT_LINK_TB_IDX2 ON DETECT_LINK_TB (OBJECT_SQ,DG_SQ,OBJECT_TYPE);
