CREATE TABLE EVENT_TB (
EV_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유 번호',
US_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL DEFAULT '00000000000000000000' COMMENT 'USER_TB 고유번호',
HB_SQ BIGINT(20) UNSIGNED DEFAULT '0' COMMENT 'HW_BASE_TB 고유번호',
RU_SQ BIGINT(20) UNSIGNED DEFAULT '0' COMMENT 'RULE_TB 고유번호',
EV_IPADDR VARCHAR(16) DEFAULT '' COMMENT '검출 IP주소',
EV_TYPE SMALLINT(3) DEFAULT '0' COMMENT '이벤트 유형',
EV_LEVEL SMALLINT(3) DEFAULT '0' COMMENT '이벤트 레벨0:DROP,1:PASS,2:INFO,3:CAUT,4:WARN,5:DANG',
EV_EXIST TINYINT(2) NOT NULL DEFAULT '1' COMMENT '0:해제,1:발생,2:중복,3:예외처리',
EV_EVENT_CONTEXT TEXT COMMENT '상세 내용',
EV_DETECT_TIME DATETIME DEFAULT NULL COMMENT 'AGENT 최초 검출 시간',
EV_DUP_DETECT_TIME DATETIME DEFAULT NULL COMMENT '가장 최근 데이터 중복 검출 시간',
EV_RECORD_TIME DATETIME DEFAULT NULL COMMENT '이벤트 최초 또는 중복 DB  기록 시간',
PRIMARY KEY (EV_SQ)
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX EVENT_TB_IDX1 ON EVENT_TB (HB_SQ,EV_TYPE,EV_EXIST,EV_DETECT_TIME);
