CREATE TABLE {USER_HISTORY} (
USH_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
US_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT 'USER_TB 고유번호',
US_ID VARCHAR(20) DEFAULT NULL COMMENT '아이디',
US_PASSWD VARCHAR(256) DEFAULT NULL COMMENT '패스워드',
US_NAME VARCHAR(32) DEFAULT NULL COMMENT '사용자명',
US_SNO VARCHAR(32) DEFAULT NULL COMMENT '사용자 식별번호(사번)',
US_EMAIL VARCHAR(128) DEFAULT NULL COMMENT '이메일 주소',
US_PHONE VARCHAR(64) DEFAULT NULL COMMENT '전화번호',
US_CELL_PHONE VARCHAR(64) DEFAULT NULL COMMENT '핸드폰 번호',
US_IP VARCHAR(128) DEFAULT NULL COMMENT '지정 IP, 세미콜론으로 분류하여 다중입력',
US_STATE CHAR(1) DEFAULT '1' COMMENT '사용자상태',
US_DESC VARCHAR(128) DEFAULT NULL COMMENT '사용자에 대한 추가 설명',
US_DB_ROUTER TINYINT(2) DEFAULT '0' COMMENT 'DBIF라우터',
US_LOG_LEVEL TINYINT(2) DEFAULT '0' COMMENT '사용자로그레벨',
US_AUTO_SYNC CHAR(1) DEFAULT '0' COMMENT '자동동기화유무',
US_FLAG CHAR(1) DEFAULT 'A' COMMENT '스케줄러 작업 상태',
US_CREATE_TIME DATETIME DEFAULT NULL COMMENT '생성일자',
US_MODIFY_TIME DATETIME DEFAULT NULL COMMENT '수정일자',
USH_RECORD_TIME DATETIME DEFAULT NULL COMMENT '기록 시간',
PRIMARY KEY (USH_SQ)
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX {USER_HISTORY}_IDX1 ON {USER_HISTORY} (US_SQ);
CREATE INDEX {USER_HISTORY}_IDX2 ON {USER_HISTORY} (US_NAME);
CREATE INDEX {USER_HISTORY}_IDX3 ON {USER_HISTORY} (US_SNO);
CREATE INDEX {USER_HISTORY}_IDX4 ON {USER_HISTORY} (US_IP);
