CREATE TABLE SYS_OMC_ERRORLOG_TB (
CREATEDATE DATETIME COMMENT '생성일자',
MGWID INTEGER(4) COMMENT '시스템ID',
PROCESSID VARCHAR(40) COMMENT '프로세스ID',
ERRORID VARCHAR(40) COMMENT '에러ID',
ERRORLEVEL VARCHAR(10) COMMENT '에러레벨',
DETAIL VARCHAR(1000) COMMENT '상세정보',
CATEGORY VARCHAR(20) COMMENT '항목',
FLAG CHAR(1) COMMENT 'E:해지, S:발생',
ENDDATE DATETIME COMMENT '종료일자'
) ENGINE=Aria DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX SYS_OMC_ERRORLOG_TB_IDX1 ON SYS_OMC_ERRORLOG_TB (CREATEDATE); 
CREATE INDEX SYS_OMC_ERRORLOG_TB_IDX2 ON SYS_OMC_ERRORLOG_TB (FLAG,CATEGORY); 
CREATE INDEX SYS_OMC_ERRORLOG_TB_IDX3 ON SYS_OMC_ERRORLOG_TB (FLAG,ERRORID); 

