CREATE TABLE {NET_CONNECTION_HISTORY} ( 
NCH_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
NC_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT 'TB 고유번호',
NC_LOCAL_NAME VARCHAR(128) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NOT NULL COMMENT '드라이브 지정명',
NC_CONNECTION_STATE TINYINT(3) UNSIGNED NULL DEFAULT '0' COMMENT '접속 상태',
NC_CONNECTION_TYPE INT(1) UNSIGNED NULL DEFAULT '0' COMMENT '연결 분류',
NC_DESC VARCHAR(128) DEFAULT NULL COMMENT '설명',
NC_PROVIDER_NAME VARCHAR(128) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '연결에 사용되는 네트워크 공급자',
NC_REMOTE_NAME VARCHAR(128) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '원격지 이름',
NC_REMOTE_PATH VARCHAR(128) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '원격지 경로(드라이브 UNC)',
NC_DISPLAY_TYPE CHAR(16) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '원격접속 출력 종류',
NC_RESOURCE_TYPE CHAR(16) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '원격접속 자원 종류',
NC_DETECT_TIME datetime DEFAULT NULL COMMENT '데이터 검출 시간',
NC_PREV_HIST_SQ text DEFAULT NULL COMMENT '과거 히스토리 고유번호 묶음',
NC_SUMMARY text DEFAULT NULL COMMENT '변동사항',
HB_SQ BIGINT(20) UNSIGNED NOT NULL COMMENT 'HW_BASE_TB 고유번호',
US_SQ BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'USER_TB 고유번호',
NCH_RECORD_TIME DATETIME NULL COMMENT '기록시간',
PRIMARY KEY(NCH_SQ) 
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX {NET_CONNECTION_HISTORY}_IDX1 ON {NET_CONNECTION_HISTORY} (NC_SQ);
CREATE INDEX {NET_CONNECTION_HISTORY}_IDX2 ON {NET_CONNECTION_HISTORY} (HB_SQ);
CREATE INDEX {NET_CONNECTION_HISTORY}_IDX3 ON {NET_CONNECTION_HISTORY} (US_SQ);
CREATE INDEX {NET_CONNECTION_HISTORY}_IDX4 ON {NET_CONNECTION_HISTORY} (NC_DETECT_TIME);
