CREATE TABLE {USER_GROUP_LINK_HISTORY} (
UGH_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT  COMMENT '고유번호',
UG_SQ_P BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT '상위 사용자그룹 고유번호',
UG_SQ_C BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT '하위 사용자그룹 고유번호',
UG_FLAG CHAR(1) NOT NULL COMMENT '스케줄러 작업 상태',
UGH_RECORD_TIME DATETIME DEFAULT NULL COMMENT '기록시간',
PRIMARY KEY (UGH_SQ)
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX {USER_GROUP_LINK_HISTORY}_IDX1 ON {USER_GROUP_LINK_HISTORY} (UG_SQ_P,UG_SQ_C);
