CREATE TABLE STW_EVENT_TB (
STW_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유 번호',
STW_RECORD_TIME VARCHAR(10) NOT NULL COMMENT '데이터 검출 시간(WEEK)',
STW_IPADDR VARCHAR(15) NOT NULL COMMENT '이벤트발생 IP',
STW_US_SQ BIGINT(20) NOT NULL COMMENT '이벤트발생 US_SQ',
STW_UG_SQ BIGINT(20) NOT NULL COMMENT '이벤트발생 UG_SQ',
STW_TYPE SMALLINT(3) NOT NULL COMMENT '이벤트 유형',
STW_LEVEL SMALLINT(1) NOT NULL COMMENT '이벤트 레벨',
STW_EXIST SMALLINT(1) NOT NULL COMMENT '0:해제,1:발생,2:중복,3:강제확인,4:강제삭제',
STW_COUNT INT DEFAULT '0' COMMENT '합계',
PRIMARY KEY (STW_SQ),
UNIQUE KEY (STW_RECORD_TIME,STW_IPADDR,STW_US_SQ,STW_TYPE,STW_LEVEL,STW_EXIST)
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX STW_EVENT_TB_IDX1 ON STW_EVENT_TB (STW_UG_SQ);
