CREATE TABLE {OS_ACCOUNT_HISTORY} ( 
OAH_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
OA_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT 'TB 고유번호',
OA_TYPE SMALLINT(5) UNSIGNED NULL DEFAULT '0' COMMENT 'Windows 사용자 계정의 특성을 설명하는 플래그',
OA_NAME VARCHAR(64) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NOT NULL COMMENT '사용자 이름',
OA_LOCAL BOOL NULL DEFAULT '0' COMMENT '로컬 계정 여부',
OA_SID VARCHAR(64) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT 'SID',
OA_SID_TYPE SMALLINT(3) UNSIGNED NULL DEFAULT '0' COMMENT 'SID 유형을 지정하는 열거형 값',
OA_CAPTION VARCHAR(64) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '계정의 도메인 및 사용자 이름',
OA_DESC VARCHAR(256) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '설명',
OA_DISABLED BOOL NULL DEFAULT '0' COMMENT '계정 사용가능 여부',
OA_STATUS VARCHAR(32) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '계정의 현재 상태',
OA_DETECT_TIME DATETIME DEFAULT NULL COMMENT '데이터 검출 시간',
OA_PREV_HIST_SQ TEXT DEFAULT NULL COMMENT '과거 히스토리 고유번호 묶음',
OA_SUMMARY TEXT DEFAULT NULL COMMENT '변동사항',
HB_SQ BIGINT(20) UNSIGNED NOT NULL COMMENT 'HW_BASE_TB 고유번호',
US_SQ BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'USER_TB 고유번호',
OAH_RECORD_TIME DATETIME NULL COMMENT '기록시간',
PRIMARY KEY(OAH_SQ) 
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX {OS_ACCOUNT_HISTORY}_IDX1 ON {OS_ACCOUNT_HISTORY} (OA_SQ);
CREATE INDEX {OS_ACCOUNT_HISTORY}_IDX2 ON {OS_ACCOUNT_HISTORY} (HB_SQ);
CREATE INDEX {OS_ACCOUNT_HISTORY}_IDX3 ON {OS_ACCOUNT_HISTORY} (US_SQ);
