CREATE TABLE {RDP_SESSION_HISTORY} ( 
RDPH_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
RDP_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT 'TB 고유번호',
RDP_CLIENT_IP VARCHAR(15) DEFAULT '' COMMENT '사용자IP',
RDP_CLIENT_NAME VARCHAR(128) DEFAULT ''  COMMENT '클라이언트 도메인명',
RDP_CONNECT_TIME CHAR(19) DEFAULT '' COMMENT '접속시간',
RDP_USER_ID VARCHAR(30) DEFAULT '' COMMENT '사용자ID',
RDP_DETECT_TIME DATETIME DEFAULT NULL COMMENT '데이터 검출 시간',
RDP_PREV_HIST_SQ TEXT DEFAULT NULL COMMENT '과거 히스토리 고유번호 묶음',
RDP_SUMMARY TEXT DEFAULT NULL COMMENT '변동사항',
HB_SQ BIGINT(20) UNSIGNED NOT NULL COMMENT 'HW_BASE_TB 고유번호',
US_SQ BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'USER_TB 고유번호',
RDPH_RECORD_TIME DATETIME NULL COMMENT '기록시간',
PRIMARY KEY(RDPH_SQ) 
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX {RDP_SESSION_HISTORY}_IDX1 ON {RDP_SESSION_HISTORY} (RDP_SQ);
CREATE INDEX {RDP_SESSION_HISTORY}_IDX2 ON {RDP_SESSION_HISTORY} (HB_SQ);
CREATE INDEX {RDP_SESSION_HISTORY}_IDX3 ON {RDP_SESSION_HISTORY} (US_SQ);
CREATE INDEX {RDP_SESSION_HISTORY}_IDX4 ON {RDP_SESSION_HISTORY} (RDP_DETECT_TIME);
