CREATE VIEW VW_EVENT_TB AS SELECT
A.EV_DETECT_TIME AS EV_DETECT_TIME,
A.EV_DUP_DETECT_TIME AS EV_DUP_DETECT_TIME,
A.EV_SQ AS EV_SQ,
A.HB_SQ AS HB_SQ,
A.US_SQ AS US_SQ,
A.EV_IPADDR AS EV_IPADDR,
A.EV_TYPE AS EV_TYPE,
A.EV_LEVEL AS EV_LEVEL,
A.EV_EXIST AS EV_EXIST,
B.HB_UNQ AS HB_UNQ,
B.HB_ACCESS_MAC AS HB_ACCESS_MAC,
B.HB_AGENT_VER AS HB_AGENT_VER,
C.US_EMAIL AS US_EMAIL,
C.US_DESC AS US_DESC
FROM DAP_DB.EVENT_TB A 
LEFT JOIN HW_BASE_TB B ON A.HB_SQ = B.HB_SQ 
LEFT JOIN USER_TB C ON A.US_SQ = C.US_SQ;
