CREATE TABLE {SHARE_FOLDER_HISTORY} ( 
SFH_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
SF_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT 'TB 고유번호',
SF_NAME VARCHAR(128) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NOT NULL COMMENT 'Windows를 실행하는 컴퓨터 시스템에서 공유로 설정된 경로에 지정된 별칭',
SF_TYPE INT(10) UNSIGNED NULL DEFAULT '0' COMMENT '공유되는 자원의 유형',
SF_PATH VARCHAR(256) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '공유의 로컬 경로',
SF_STATUS VARCHAR(10) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '현재 상태를 나타내는 문자열',
SF_DETECT_TIME DATETIME DEFAULT NULL COMMENT '데이터 검출 시간',
SF_PREV_HIST_SQ TEXT DEFAULT NULL COMMENT '과거 히스토리 고유번호 묶음',
SF_SUMMARY TEXT DEFAULT NULL COMMENT '변동사항',
HB_SQ BIGINT(20) UNSIGNED NOT NULL COMMENT 'HW_BASE_TB 고유번호',
US_SQ BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'USER_TB 고유번호',
SFH_RECORD_TIME DATETIME NULL COMMENT '기록시간',
PRIMARY KEY(SFH_SQ) 
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX {SHARE_FOLDER_HISTORY}_IDX1 ON {SHARE_FOLDER_HISTORY} (SF_SQ);
CREATE INDEX {SHARE_FOLDER_HISTORY}_IDX2 ON {SHARE_FOLDER_HISTORY} (HB_SQ);
CREATE INDEX {SHARE_FOLDER_HISTORY}_IDX3 ON {SHARE_FOLDER_HISTORY} (US_SQ);
CREATE INDEX {SHARE_FOLDER_HISTORY}_IDX4 ON {SHARE_FOLDER_HISTORY} (SF_DETECT_TIME);
