CREATE TABLE DETECT_GROUP_TB (
DG_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
DG_NAME char(32) NOT NULL COMMENT '프로세스or IP 그룹명',
DG_SNO CHAR(32) DEFAULT '' COMMENT '프로세스 OR IP 그룹 식별번호',
DG_DESC CHAR(128) DEFAULT '' COMMENT '프로세스 OR IP 그룹에 대한 추가 설명',
DG_FLAG CHAR(1) DEFAULT 'A' COMMENT '스케줄러 작업 상태',
PRIMARY KEY (DG_SQ),
UNIQUE KEY DG_NAME_UK (DG_NAME)
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
