CREATE TABLE {SYSTEM_HISTORY} ( 
STH_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
ST_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT 'TB 고유번호',
ST_NAME VARCHAR(64) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NOT NULL COMMENT '시스템 이름',
ST_DNS_HOST_NAME VARCHAR(64) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '호스트 이름',
ST_DOMAIN VARCHAR(64) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '도메인 이름',
ST_DOMAIN_ROLE INT(5) UNSIGNED NULL DEFAULT '0' COMMENT '할당된 도메인 작업 그룹에서 컴퓨터의 역할',
ST_TIME_ZONE INT(5) UNSIGNED NULL DEFAULT '0' COMMENT '단위 컴퓨터 시스템이 UTC에서 오프셋된 시간',
ST_WAKEUP_TYPE INT(5) UNSIGNED NULL DEFAULT '0' COMMENT '시스템의 전원을 켜는 이벤트',
ST_WORK_GROUP VARCHAR(256) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '컴퓨터의 작업 그룹 이름',
ST_BOOTUP_STATE VARCHAR(64) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '시스템 부팅 상태',
ST_MEMORY INT UNSIGNED DEFAULT '0' COMMENT '메모리 정보',
ST_VGA VARCHAR(32) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '그래픽카드정보',
ST_VM_NAME VARCHAR(64) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '현재 시스템이 가상머신인 경우, 가상머신 이름',
ST_INSTALLED_VM TEXT NULL COMMENT '설치된 가상머신 목록, 세미콜론으로으로 분리해서 다중입력',
ST_DETECT_TIME DATETIME DEFAULT NULL COMMENT '데이터 검출 시간',
ST_PREV_HIST_SQ TEXT DEFAULT NULL COMMENT '과거 히스토리 고유번호 묶음',
ST_SUMMARY TEXT DEFAULT NULL COMMENT '변동사항',
HB_SQ BIGINT(20) UNSIGNED NOT NULL COMMENT 'HW_BASE_TB 고유번호',
US_SQ BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'USER_TB 고유번호',
STH_RECORD_TIME DATETIME NULL COMMENT '기록시간',
PRIMARY KEY(STH_SQ) 
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX {SYSTEM_HISTORY}_IDX1 ON {SYSTEM_HISTORY} (ST_SQ);
CREATE INDEX {SYSTEM_HISTORY}_IDX2 ON {SYSTEM_HISTORY} (HB_SQ);
CREATE INDEX {SYSTEM_HISTORY}_IDX3 ON {SYSTEM_HISTORY} (US_SQ);
CREATE INDEX {SYSTEM_HISTORY}_IDX4 ON {SYSTEM_HISTORY} (ST_DETECT_TIME);
