CREATE TABLE DETECT_GROUP_LINK_TB (
DG_SQ_P BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT '상위 감시 그룹 고유번호',
DG_SQ_C BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT '하위 감시 그룹 고유번호',
DGL_FLAG CHAR(1) DEFAULT 'A' COMMENT '스케줄러 작업 상태'
) ENGINE=Aria DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX DETECT_GROUP_LINK_TB_IDX1 ON DETECT_GROUP_LINK_TB (DGL_FLAG);
