CREATE TABLE {RULE_SCHEDULE_HISTORY} (
RSH_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
RS_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT '고유번호',
RU_SQ BIGINT(20) UNSIGNED ZEROFILL NULL COMMENT '정책 고유번호',
RS_NAME VARCHAR(32) NOT NULL DEFAULT '스케쥴명',
RS_TYPE TINYINT(2) NOT NULL DEFAULT '0' COMMENT '0:지정일,1:매일,2:매주,3:매월(일자),4:매월(주간)',
RS_WEEKOFDAY VARCHAR(20) NOT NULL DEFAULT '0' COMMENT '1W,2W,3W...',
RS_DAYOFWEEK VARCHAR(30) NOT NULL DEFAULT '0' COMMENT 'SUN,MON,TUE,WED...',
RS_DAY VARCHAR(100) NOT NULL DEFAULT '0' COMMENT '01,02,03...',
RS_DATE CHAR(17) NOT NULL DEFAULT '' COMMENT 'YYYYMMDD~YYYYMMDD',
RS_TIME CHAR(13) NOT NULL DEFAULT '' COMMENT 'HHMMSS~HHMMSS',
RS_EXCEPTION TINYINT(1) NOT NULL DEFAULT '0' COMMENT '0:POSITIVE, 1:NEGATIVE', 
RS_USE TINYINT(1) NOT NULL DEFAULT '0' COMMENT '0:NOTUSE, 1:USE',
RS_FLAG CHAR(1) DEFAULT 'A' COMMENT '스케줄러 작업 상태',
RSH_RECORD_TIME datetime DEFAULT NULL COMMENT '기록 시간',
PRIMARY KEY (RSH_SQ)
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX {RULE_SCHEDULE_HISTORY}_IDX1 ON {RULE_SCHEDULE_HISTORY} (RS_FLAG);
CREATE INDEX {RULE_SCHEDULE_HISTORY}_IDX2 ON {RULE_SCHEDULE_HISTORY} (RU_SQ,RS_TYPE);
