CREATE TABLE CPU_TB (
CU_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
CU_NAME VARCHAR(128) DEFAULT '' COMMENT '이름',
CU_MF VARCHAR(128) DEFAULT '' COMMENT '제작사',
CU_DESC VARCHAR(256) DEFAULT '' COMMENT '설명',
CU_PID VARCHAR(32) DEFAULT '' COMMENT '프로세서 ID',
CU_DETECT_TIME DATETIME DEFAULT NULL COMMENT '데이터 검출 시간',
CU_CURR_HIST_SQ BIGINT(20) UNSIGNED DEFAULT NULL COMMENT '현재 히스토리 고유번호',
CU_CURR_HIST_DATE VARCHAR(8) DEFAULT NULL COMMENT '현재 히스토리 날짜',
CU_PREV_HIST_SQ TEXT DEFAULT NULL COMMENT '과거 히스토리 고유번호 묶음',
CU_SUMMARY TEXT DEFAULT NULL COMMENT '변동사항',
HB_SQ BIGINT(20) UNSIGNED NOT NULL COMMENT 'HW_BASE_TB 고유번호',
US_SQ BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'USER_TB 고유번호',
PRIMARY KEY (CU_SQ)
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page; 
CREATE INDEX CPU_TB_IDX1 ON CPU_TB (HB_SQ);
CREATE INDEX CPU_TB_IDX2 ON CPU_TB (US_SQ);
