CREATE TABLE SYS_THRESHOLD_TB (
MGWID INTEGER(4) NOT NULL COMMENT '시스템ID',
ELEMENT VARCHAR(20)	NOT NULL COMMENT '항목',
CRITICAL INTEGER(9) COMMENT 'CRITICAL 한계치',
MAJOR INTEGER(9) COMMENT 'MAJOR 한계치',
MINOR INTEGER(9) COMMENT 'MINOR 한계치',
PRIMARY KEY(MGWID,ELEMENT)
) ENGINE=Aria DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;

