CREATE VIEW VW_DISK_CHANGE AS SELECT 
A.HB_SQ AS HB_SQ, 
A.DK_NAME AS CURR_DISK, 
A.DK_DESC AS CURR_DESC, 
A.DK_PHYSICAL_SN AS CURR_PHYSICAL_SN, 
A.DK_DETECT_TIME AS CURR_DETECT_TIME,
B.DK_NAME AS BEF1_DISK, 
B.DK_DESC AS BEF1_DESC, 
B.DK_PHYSICAL_SN AS BEF1_PHYSICAL_SN, 
B.DK_DETECT_TIME AS BEF1_DETECT_TIME,
C.DK_NAME AS BEF2_DISK, 
C.DK_DESC AS BEF2_DESC, 
C.DK_PHYSICAL_SN AS BEF2_PHYSICAL_SN, 
C.DK_DETECT_TIME AS BEF2_DETECT_TIME
FROM DAP_DB.DISK_TB A 
LEFT JOIN DAP_HISTORY_2018.DISK_HISTORY_09 B ON A.HB_SQ = B.HB_SQ AND A.DK_PHYSICAL_SN = B.DK_PHYSICAL_SN 
LEFT JOIN DAP_HISTORY_2018.DISK_HISTORY_08 C ON A.HB_SQ = C.HB_SQ AND A.DK_PHYSICAL_SN = C.DK_PHYSICAL_SN
GROUP BY A.HB_SQ, A.DK_PHYSICAL_SN ORDER BY A.HB_SQ;
