CREATE TABLE RDP_SESSION_TB (
RDP_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
RDP_CLIENT_IP VARCHAR(15) DEFAULT '' COMMENT '사용자IP',
RDP_CLIENT_NAME VARCHAR(128) DEFAULT ''  COMMENT '클라이언트 도메인명',
RDP_CONNECT_TIME CHAR(19) DEFAULT '' COMMENT '접속시간',
RDP_USER_ID VARCHAR(30) DEFAULT '' COMMENT '사용자ID',
RDP_DETECT_TIME DATETIME DEFAULT NULL COMMENT '데이터 검출 시간',
RDP_CURR_HIST_SQ BIGINT(20) UNSIGNED DEFAULT NULL COMMENT '현재 히스토리 고유번호',
RDP_CURR_HIST_DATE VARCHAR(8) DEFAULT NULL COMMENT '현재 히스토리 날짜',
RDP_PREV_HIST_SQ TEXT DEFAULT NULL COMMENT '과거 히스토리 고유번호 묶음',
RDP_SUMMARY TEXT DEFAULT NULL COMMENT '변동사항',
HB_SQ BIGINT(20) UNSIGNED NOT NULL COMMENT 'HW_BASE_TB 고유번호',
US_SQ BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'USER_TB 고유번호',
PRIMARY KEY (RDP_SQ)
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX RDP_SESSION_TB_IDX1 ON RDP_SESSION_TB (HB_SQ);
CREATE INDEX RDP_SESSION_TB_IDX2 ON RDP_SESSION_TB (US_SQ);
CREATE INDEX RDP_SESSION_TB_IDX3 ON RDP_SESSION_TB (RDP_CLIENT_IP,RDP_USER_ID);
