CREATE TABLE {DETECT_GROUP_LINK_HISTORY} (
DGLH_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT  COMMENT '고유번호',
DG_SQ_P BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT '상위 감시 그룹 고유번호',
DG_SQ_C BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT '하위 감시 그룹 고유번호',
DGL_FLAG CHAR(1) NOT NULL COMMENT '스케줄러 작업 상태',
DGLH_RECORD_TIME DATETIME DEFAULT NULL COMMENT '기록시간',
PRIMARY KEY (DGLH_SQ)
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page; 
CREATE INDEX {DETECT_GROUP_LINK_HISTORY}_IDX1 ON {DETECT_GROUP_LINK_HISTORY} (DG_SQ_P,DG_SQ_C);
