CREATE TABLE USER_GROUP_TB (
UG_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
UG_CODE VARCHAR(10) DEFAULT NULL COMMENT '부서코드',
UG_NAME VARCHAR(100) NOT NULL COMMENT '부서명',
UG_DESC VARCHAR(128) DEFAULT '' COMMENT '부서에 대한 추가 설명',
UG_MANAGER VARCHAR(32) DEFAULT '' COMMENT '부서장',
UG_DATE VARCHAR(10) DEFAULT '' COMMENT '유효기간',
UG_USE CHAR(1) DEFAULT 'Y'  COMMENT '사용유무',
UG_CREATE_TIME DATETIME DEFAULT NULL COMMENT '생성일자',
UG_MODIFY_TIME DATETIME DEFAULT NULL COMMENT '수정일자',
UG_FLAG CHAR(1) DEFAULT 'A' COMMENT '스케줄러 작업 상태',
UG_AUTO_SYNC    CHAR(1) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '0' COMMENT '자동동기화유무',
PRIMARY KEY (UG_SQ),
UNIQUE KEY (UG_CODE)
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX USER_GROUP_TB_IDX1 ON USER_GROUP_TB (UG_NAME);
