CREATE TABLE MANAGER_EVENT_TB (
MNE_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
MN_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT 'MANAGER_TB 고유번호',
MNE_ACTION_TYPE SMALLINT(3) UNSIGNED DEFAULT '0' COMMENT '사용자 로그 종류 (MANAGER에서 정의)',
MNE_ACTION_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL DEFAULT '00000000000000000000' COMMENT '이벤트가 발생한  고유번호',
MNE_IPADDR CHAR(16) DEFAULT '' COMMENT '접속 IP주소',
MNE_EMAIL VARCHAR(64) DEFAULT NULL COMMENT '이메일 주소',
MNE_CELL_PHONE CHAR(32) DEFAULT NULL COMMENT '핸드폰 번호',
MNE_RECORD_TIME DATETIME DEFAULT NULL COMMENT '기록시간',
MNE_SUMMARY TEXT DEFAULT NULL COMMENT '이벤트요약',
MNE_FLAG CHAR(1) DEFAULT 'A' COMMENT '스케줄러작업상태',
PRIMARY KEY (MNE_SQ)
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
