CREATE TABLE CONNECT_EXT_TB (
CE_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
CE_URL VARCHAR(64) NOT NULL COMMENT '접속 URL',
CE_CONNECTED TINYINT(3) UNSIGNED DEFAULT '0' COMMENT '접속 PORT',
CE_DETECT_TIME DATETIME DEFAULT NULL COMMENT '데이터 검출 시간',
CE_CURR_HIST_SQ BIGINT(20) UNSIGNED DEFAULT NULL COMMENT '현재 히스토리 고유번호',
CE_CURR_HIST_DATE VARCHAR(8) DEFAULT NULL COMMENT '현재 히스토리 날짜',
CE_PREV_HIST_SQ TEXT DEFAULT NULL COMMENT '과거 히스토리 고유번호 묶음',
CE_SUMMARY TEXT DEFAULT NULL COMMENT '변동사항',
HB_SQ BIGINT(20) UNSIGNED NOT NULL COMMENT 'HW_BASE_TB 고유번호',
US_SQ BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'USER_TB 고유번호',
PRIMARY KEY (CE_SQ)
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX CONNECT_EXT_TB_IDX1 ON CONNECT_EXT_TB (HB_SQ);
CREATE INDEX CONNECT_EXT_TB_IDX2 ON CONNECT_EXT_TB (US_SQ);
