CREATE TABLE {OS_HISTORY} ( 
OSH_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
OS_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT 'TB 고유번호',
OS_NAME VARCHAR(128) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NOT NULL COMMENT '운영체제명',
OS_VERSION VARCHAR(32) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '운영체제 버전',
OS_ARCHITECTURE VARCHAR(16) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '아키텍처',
OS_LANG INT(5) UNSIGNED NULL DEFAULT '0' COMMENT '언어',
OS_TYPE INT(5) UNSIGNED NULL DEFAULT '0' COMMENT '운영체제 유형',
OS_PORTABLE BOOL NULL DEFAULT '0' COMMENT '외부 USB 장치에서 부팅되었는지 여부',
OS_SP_MAJOR_VER INT(5) UNSIGNED NULL DEFAULT '0' COMMENT '서비스팩의 주버전 번호',
OS_SP_MINOR_VER INT(5) UNSIGNED NULL DEFAULT '0' COMMENT '서비스팩의 부버전 번호',
OS_DETECT_TIME datetime DEFAULT NULL COMMENT '데이터 검출 시간',
OS_PREV_HIST_SQ text DEFAULT NULL COMMENT '과거 히스토리 고유번호 묶음',
OS_SUMMARY text DEFAULT NULL COMMENT '변동사항',
HB_SQ BIGINT(20) UNSIGNED NOT NULL COMMENT 'HW_BASE_TB 고유번호',
US_SQ BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'USER_TB 고유번호',
OSH_RECORD_TIME DATETIME NULL COMMENT '기록시간',
PRIMARY KEY(OSH_SQ) 
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX {OS_HISTORY}_IDX1 ON {OS_HISTORY} (OS_SQ);
CREATE INDEX {OS_HISTORY}_IDX2 ON {OS_HISTORY} (HB_SQ);
CREATE INDEX {OS_HISTORY}_IDX3 ON {OS_HISTORY} (US_SQ);
