CREATE TABLE SYS_OMC_ERROR_TB (
MGWID INTEGER(4) NOT NULL COMMENT '시스템ID',
CODE CHAR(4) NOT NULL COMMENT '코드',
ERRORID varchar(40)	NOT NULL COMMENT '에러ID',
ERRORLEVEL varchar(10) NOT NULL COMMENT '에러레벨',
CONTENT varchar(100) COMMENT '상세내용',
PRIMARY KEY(MGWID,CODE)
) ENGINE=Aria DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
