CREATE TABLE {STM_EVENT_HISTORY} (
STMH_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
STM_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT 'TB 고유번호',
STM_RECORD_TIME VARCHAR(7) NOT NULL COMMENT '데이터 검출 시간(MONTH)',
STM_IPADDR VARCHAR(15) NOT NULL COMMENT '이벤트발생 IP',
STM_US_SQ BIGINT(20) NOT NULL COMMENT '이벤트발생 US_SQ',
STM_UG_SQ BIGINT(20) NOT NULL COMMENT '이벤트발생 UG_SQ',
STM_TYPE SMALLINT(3) NOT NULL COMMENT '이벤트 유형',
STM_LEVEL SMALLINT(1) NOT NULL COMMENT '이벤트 레벨 주의(1) 카운트',
STM_EXIST SMALLINT(1) NOT NULL COMMENT '0:해제,1:발생,2:중복,3:강제확인,4:강제삭제',
STM_COUNT INT DEFAULT '0' COMMENT '합계',
STMH_RECORD_TIME DATETIME NOT NULL COMMENT '기록시간',
PRIMARY KEY (STMH_SQ),
UNIQUE KEY (STM_RECORD_TIME,STM_IPADDR,STM_US_SQ,STM_TYPE,STM_LEVEL,STM_EXIST)
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX {STM_EVENT_HISTORY}_IDX1 ON {STM_EVENT_HISTORY} (STM_UG_SQ);
