CREATE TABLE NET_SCAN_TB (
NS_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
NS_DAP_AGENT TINYINT(1) DEFAULT '0' COMMENT '접속 가능 여부',
NS_IP VARCHAR(15) DEFAULT ''  COMMENT '검출된IP주소',
NS_MAC VARCHAR(17) DEFAULT '' COMMENT '검출된MAC주소',
NS_MAC_MATCH TINYINT(1) DEFAULT '0' COMMENT '원격지에서확인한MAC주소와DAPAGENT와주소일치여부',
NS_WEB_TEXT VARCHAR(128) DEFAULT '' COMMENT '접속 후 수신한 문자열에서 검출한 키워드(EX. IPTIME, ETC)',
NS_OPEN_PORT TEXT COMMENT '열린 PORT 번호 목록, 세미콜론으로 분리해서 다중입력',
NS_DETECT_TIME DATETIME DEFAULT NULL COMMENT '데이터 검출 시간',
NS_CURR_HIST_SQ BIGINT(20) UNSIGNED DEFAULT NULL COMMENT '현재 히스토리 고유번호',
NS_CURR_HIST_DATE VARCHAR(8) DEFAULT NULL COMMENT '현재 히스토리 날짜',
NS_PREV_HIST_SQ TEXT DEFAULT NULL COMMENT '과거 히스토리 고유번호 묶음',
HB_SQ BIGINT(20) UNSIGNED NOT NULL COMMENT 'HW_BASE_TB 고유번호',
US_SQ BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'USER_TB 고유번호',
PRIMARY KEY (NS_SQ),
UNIQUE KEY NET_SCAN_TB_UK (NS_IP,NS_MAC)
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX NET_SCAN_TB_IDX1 ON NET_SCAN_TB (HB_SQ);
CREATE INDEX NET_SCAN_TB_IDX2 ON NET_SCAN_TB (US_SQ);
