CREATE TABLE {USER_GROUP_HISTORY} (
UGH_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
UG_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT 'USER_GROUP_TB 고유번호',
UG_CODE VARCHAR(10) DEFAULT NULL COMMENT '부서코드',
UG_NAME VARCHAR(100) NOT NULL COMMENT '부서명',
UG_DESC VARCHAR(128) DEFAULT '' COMMENT '부서에 대한 추가 설명',
UG_MANAGER VARCHAR(32) DEFAULT '' COMMENT '부서장',
UG_DATE VARCHAR(10) DEFAULT '' COMMENT '부서날짜',
UG_USE CHAR(1) DEFAULT 'Y'  COMMENT '사용유무',
UG_CREATE_TIME DATETIME DEFAULT NULL COMMENT '생성일자',
UG_MODIFY_TIME DATETIME DEFAULT NULL COMMENT '수정일자',
UG_FLAG CHAR(1) DEFAULT 'A' COMMENT '스케줄러 작업 상태',
UGH_RECORD_TIME DATETIME DEFAULT NULL COMMENT '기록 시간',
PRIMARY KEY (UGH_SQ)
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX {USER_GROUP_HISTORY}_IDX1 ON {USER_GROUP_HISTORY} (UG_SQ);
CREATE INDEX {USER_GROUP_HISTORY}_IDX2 ON {USER_GROUP_HISTORY} (UG_CODE);
CREATE INDEX {USER_GROUP_HISTORY}_IDX3 ON {USER_GROUP_HISTORY} (UG_NAME);
