CREATE TABLE DETECT_PRINTER_PORT_TB (
PP_PORT SMALLINT(3) NOT NULL COMMENT '접속 검사대상 프린터 포트',
PP_DESC VARCHAR(128) DEFAULT '' COMMENT '포트 정보에 대한 추가 설명',
PP_USE TINYINT(1) DEFAULT '1' COMMENT '등록정보 사용 여부',
PP_FLAG CHAR(1) DEFAULT 'A' COMMENT '스케줄러 작업 상태',
PRIMARY KEY (PP_PORT)
) ENGINE=Aria DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
