CREATE TABLE SYS_QUEUE_TB (
MGWID INTEGER(4) NOT NULL COMMENT '시스템ID',
TOTAL INTEGER DEFAULT 0 COMMENT '할당된 총 개수',
USED INTEGER DEFAULT 0 COMMENT '사용중인 개수',
AVAIL INTEGER DEFAULT 0 COMMENT '사용가능한 개수',
NAME varchar(30) NOT NULL COMMENT '큐 이름',
PRIMARY KEY(MGWID,NAME)
) ENGINE=Aria DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
