CREATE TABLE DISK_TB (
DK_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
DK_NAME VARCHAR(128) NOT NULL COMMENT '이름',
DK_DRIVE_TYPE INT(10) UNSIGNED DEFAULT '0' COMMENT '드라이브 유형',
DK_FILE_SYSTEM VARCHAR(32) DEFAULT '' COMMENT '파일시스템 종류',
DK_ACCESS TINYINT(3) UNSIGNED DEFAULT '0' COMMENT '미디어 엑세스 유형',
DK_VOLUME_NAME VARCHAR(32) DEFAULT '' COMMENT '볼륨명',
DK_VOLUME_SN VARCHAR(16) DEFAULT '' COMMENT '볼륨 시리얼 번호',
DK_DESC VARCHAR(256) DEFAULT '' COMMENT '설명',
DK_PHYSICAL_SN VARCHAR(64) DEFAULT '' COMMENT '시리얼 번호',
DK_INTERFACE_TYPE VARCHAR(32) DEFAULT '' COMMENT '인터페이스 종류',
DK_MF VARCHAR(128) DEFAULT '' COMMENT '제조사',
DK_MODEL VARCHAR(64) DEFAULT '' COMMENT '모델명',
DK_DETECT_TIME DATETIME DEFAULT NULL COMMENT '데이터 검출 시간',
DK_CURR_HIST_SQ BIGINT(20) UNSIGNED DEFAULT NULL COMMENT '현재 히스토리 고유번호',
DK_CURR_HIST_DATE VARCHAR(8) DEFAULT NULL COMMENT '현재 히스토리 날짜',
DK_PREV_HIST_SQ TEXT DEFAULT NULL COMMENT '과거 히스토리 고유번호 묶음',
DK_SUMMARY TEXT DEFAULT NULL COMMENT '변동사항',
HB_SQ BIGINT(20) UNSIGNED NOT NULL COMMENT 'HW_BASE_TB 고유번호',
US_SQ BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'USER_TB 고유번호',
PRIMARY KEY (DK_SQ)
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX DISK_TB_IDX1 ON DISK_TB (HB_SQ);
CREATE INDEX DISK_TB_IDX2 ON DISK_TB (US_SQ);
