CREATE TABLE {WIFI_HISTORY} ( 
WFH_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '고유번호',
WF_SQ BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT '고유번호',
WF_INTERFACE_STATUS SMALLINT(3) UNSIGNED NULL DEFAULT '4' COMMENT '인터페이스 상태정보',
WF_INTERFACE_DESC VARCHAR(256) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '인터페이스 설명',
WF_CONNECTION_MODE SMALLINT(3) UNSIGNED NULL DEFAULT '5' COMMENT '접속 모드',
WF_PROFILE_NAME VARCHAR(64) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT '접속 프로파일명',
WF_SSID VARCHAR(64) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT 'SSID명',
WF_BSS_NETWORK_TYPE SMALLINT(3) UNSIGNED NULL DEFAULT '0' COMMENT 'BSS네트워크 타입',
WF_MAC_ADDR VARCHAR(32) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT '' COMMENT 'MAC 주소',
WF_PHY_NETWORK_TYPE INT(10) UNSIGNED NULL DEFAULT '0' COMMENT 'PHY 네트워크 타입',
WF_SECURITY BOOL NULL DEFAULT '0' COMMENT '보안 활성화 여부',
WF_8021X BOOL NULL DEFAULT '0' COMMENT '802.1X 여부',
WF_AUTH_ALGO INT(10) UNSIGNED NULL DEFAULT '0' COMMENT '인증 알고리즘',
WF_CIPHER_ALGO INT(10) UNSIGNED NULL DEFAULT '0' COMMENT 'Cipher 알고리즘',
WF_DETECT_TIME DATETIME DEFAULT NULL COMMENT '데이터 검출 시간',
WF_PREV_HIST_SQ TEXT DEFAULT NULL COMMENT '과거 히스토리 고유번호 묶음',
WF_SUMMARY TEXT DEFAULT NULL COMMENT '변동사항',
HB_SQ BIGINT(20) UNSIGNED NOT NULL COMMENT 'HW_BASE_TB 고유번호',
US_SQ BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'USER_TB 고유번호',
WFH_RECORD_TIME DATETIME NULL COMMENT '기록 시간',
PRIMARY KEY(WFH_SQ) 
) ENGINE=Aria AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci PAGE_CHECKSUM=1 ROW_FORMAT=Page;
CREATE INDEX {WIFI_HISTORY}_IDX1 ON {WIFI_HISTORY} (WF_SQ);
CREATE INDEX {WIFI_HISTORY}_IDX2 ON {WIFI_HISTORY} (HB_SQ);
CREATE INDEX {WIFI_HISTORY}_IDX3 ON {WIFI_HISTORY} (US_SQ);
CREATE INDEX {WIFI_HISTORY}_IDX4 ON {WIFI_HISTORY} (WF_DETECT_TIME);
